apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
spec:
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: nginx-svc
              port:
                number: 80
        - path: /node
          pathType: Prefix
          backend:
            service:
              name: node-svc
              port:
                number: 80
        - path: /php
          pathType: Prefix
          backend:
            service:
              name: php-svc
              port:
                number: 80