apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    name: api
spec:
  selector:
    matchLabels:
      name: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
        name: api
    spec:
      containers:
        - name: api
          image: vutruong1998/node-cicd-k8s:node
          imagePullPolicy: Always
          ports:
            - name: api
              containerPort: 3000
          env:
            - name: REDIS_URI
              value: redis://redis:6379
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    name: api-service
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  ports:
    - port: 80
      name: http
      targetPort: 3000
      protocol: TCP
      nodePort: 31080

  selector:
    app: api

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-ingress
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: api-service
              servicePort: 80