# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: node-cicd-k8s
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: nodeapp
#   template:
#     metadata:
#       labels:
#         app: nodeapp
#     spec:
#       containers:
#       - name: node-cicd-k8s
#         image: vutruong1998/node-cicd-k8s:node
#         imagePullPolicy: "Always"
#         ports:
#         - containerPort: 3000
#         resources:
#           requests:
#             memory: 64Mi
#             cpu: 100m
#           limits:
#             memory: 128Mi
#             cpu: 300m
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: node-cicd-k8s
# spec:
#   # trùng với label của POD tại Deployment
#   selector:
#     app: nodeapp
#   type: NodePort
#   ports:
#     - protocol: TCP
#       # cổng dịch vụ ánh xạ vào cổng POD
#       port: 80
#       # cổng POD ánh xạ vào container
#       targetPort: 3000
#       # cổng NODE ánh xạ vào cổng dịch vụ (30000-32767)
#       nodePort: 31080

# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: api-ingress
# spec:
#   rules:
#     - http:
#         paths:
#           - path: /*
#             backend:
#               serviceName: node-cicd-k8s
#               servicePort: 80