apiVersion: v1
kind: Service
metadata:
  name: example-service
  labels:
    name: "{{ .Values.name }}"
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  ports:
    - port: 80
      name: http
      targetPort: 3000
      protocol: TCP
      # nodePort: 31080

  selector:
    app: "{{ .Values.name }}"
