apiVersion: v1
kind: Secret
metadata:
  name: microservice-secret
data:
  redis-uri: cmVkaXM6Ly9yZWRpczo2Mzc5
  mongo-uri: bW9uZ29kYjovL21vbmdvL2s4cw==

# encode : echo -n redis://redis:6379 | base64
# decode : echo -n cmVkaXM6Ly9yZWRpczo2Mzc5 | base64 -- decode
# describe secret : kubectl describe secret/microservice-secret